/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedLeaderboardRouteImport } from './routes/_authenticated/leaderboard'
import { Route as AuthenticatedBattleRouteImport } from './routes/_authenticated/battle'
import { Route as AuthenticatedWorkoutExerciseIdRouteImport } from './routes/_authenticated/workout.$exerciseId'
import { Route as AuthenticatedBattleIdRouteImport } from './routes/_authenticated/battle.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeaderboardRoute =
  AuthenticatedLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBattleRoute = AuthenticatedBattleRouteImport.update({
  id: '/battle',
  path: '/battle',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWorkoutExerciseIdRoute =
  AuthenticatedWorkoutExerciseIdRouteImport.update({
    id: '/workout/$exerciseId',
    path: '/workout/$exerciseId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBattleIdRoute = AuthenticatedBattleIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedBattleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/battle': typeof AuthenticatedBattleRouteWithChildren
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/battle/$id': typeof AuthenticatedBattleIdRoute
  '/workout/$exerciseId': typeof AuthenticatedWorkoutExerciseIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/battle': typeof AuthenticatedBattleRouteWithChildren
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/': typeof AuthenticatedIndexRoute
  '/battle/$id': typeof AuthenticatedBattleIdRoute
  '/workout/$exerciseId': typeof AuthenticatedWorkoutExerciseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/battle': typeof AuthenticatedBattleRouteWithChildren
  '/_authenticated/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/battle/$id': typeof AuthenticatedBattleIdRoute
  '/_authenticated/workout/$exerciseId': typeof AuthenticatedWorkoutExerciseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/battle'
    | '/leaderboard'
    | '/profile'
    | '/battle/$id'
    | '/workout/$exerciseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/battle'
    | '/leaderboard'
    | '/profile'
    | '/'
    | '/battle/$id'
    | '/workout/$exerciseId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/battle'
    | '/_authenticated/leaderboard'
    | '/_authenticated/profile'
    | '/_authenticated/'
    | '/_authenticated/battle/$id'
    | '/_authenticated/workout/$exerciseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leaderboard': {
      id: '/_authenticated/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthenticatedLeaderboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/battle': {
      id: '/_authenticated/battle'
      path: '/battle'
      fullPath: '/battle'
      preLoaderRoute: typeof AuthenticatedBattleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workout/$exerciseId': {
      id: '/_authenticated/workout/$exerciseId'
      path: '/workout/$exerciseId'
      fullPath: '/workout/$exerciseId'
      preLoaderRoute: typeof AuthenticatedWorkoutExerciseIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/battle/$id': {
      id: '/_authenticated/battle/$id'
      path: '/$id'
      fullPath: '/battle/$id'
      preLoaderRoute: typeof AuthenticatedBattleIdRouteImport
      parentRoute: typeof AuthenticatedBattleRoute
    }
  }
}

interface AuthenticatedBattleRouteChildren {
  AuthenticatedBattleIdRoute: typeof AuthenticatedBattleIdRoute
}

const AuthenticatedBattleRouteChildren: AuthenticatedBattleRouteChildren = {
  AuthenticatedBattleIdRoute: AuthenticatedBattleIdRoute,
}

const AuthenticatedBattleRouteWithChildren =
  AuthenticatedBattleRoute._addFileChildren(AuthenticatedBattleRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBattleRoute: typeof AuthenticatedBattleRouteWithChildren
  AuthenticatedLeaderboardRoute: typeof AuthenticatedLeaderboardRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedWorkoutExerciseIdRoute: typeof AuthenticatedWorkoutExerciseIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBattleRoute: AuthenticatedBattleRouteWithChildren,
  AuthenticatedLeaderboardRoute: AuthenticatedLeaderboardRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedWorkoutExerciseIdRoute: AuthenticatedWorkoutExerciseIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
